categories = [
	{"title":"92 X 52 ВИЗИТКА СО СКРУГЛЕНИЕМ УГЛОВ", "title_eng":"Vizitka so skrugleniem", "category":"Визитки", "category_id":"4" ,"table_name":"vizitki"},
{"title":"92 X 52 ВИЗИТКА С ОТВЕРСТИЕМ 5 ММ", "title_eng":"Vizitka s otverstiem", "category":"Визитки", "category_id":"4" ,"table_name":"vizitki"},
{"title":"92 X 52 ЭКОНОМ ВИЗИТКА", "title_eng":"Vizitka econom", "category":"Визитки", "category_id":"4" ,"table_name":"vizitki"},
{"title":"92 X 52 ВИЗИТКА", "title_eng":"Vizitka", "category":"Визитки", "category_id":"4" ,"table_name":"vizitki"},
{"title":"90 X 50 ВИЗИТКА С ЛАМИНАЦИЕЙ", "title_eng":"Vizitka s laminaciey", "category":"Визитки", "category_id":"4" ,"table_name":"vizitki"},
{"title":"52 X 182 ВИЗИТКА ДВОЙНАЯ ВЕРТИКАЛЬНАЯ", "title_eng":"Vizitka dvoinaya vertikalnaya", "category":"Визитки", "category_id":"4" ,"table_name":"vizitki"},
{"title":"92 X 102 ВИЗИТКА ДВОЙНАЯ ГОРИЗОНТАЛЬНАЯ", "title_eng":"Vizitka dvoinaya horizont", "category":"Визитки", "category_id":"4" ,"table_name":"vizitki"},
{"title":"87 X 57 ЕВРОВИЗИТКА", "title_eng":"Evrovizitka", "category":"Визитки", "category_id":"4" ,"table_name":"vizitki"},
{"title":"57 X 172 ДВОЙНАЯ ЕВРОВИЗИТКА", "title_eng":"Evrovizitka dvoinaya", "category":"Визитки", "category_id":"4" ,"table_name":"vizitki"},
{"title":"87 X 112 ДВОЙНАЯ ЕВРОВИЗИТКА ГОРИЗОНТАЛЬНАЯ", "title_eng":"Evrovizitka dvoinaya horizont", "category":"Визитки", "category_id":"4" ,"table_name":"vizitki"},
{"title":"212 X 299 ЛИСТОВКА А4", "title_eng":"Listovka A4", "category":"Листовки", "category_id":"3" ,"table_name":"listovki"},
{"title":"150 X 212 ЛИСТОВКА А5", "title_eng":"Listovka A5", "category":"Листовки", "category_id":"3" ,"table_name":"listovki"},
{"title":"107 X 150 ЛИСТОВКА А6", "title_eng":"Listovka A6", "category":"Листовки", "category_id":"3" ,"table_name":"listovki"},
{"title":"76 X 107 ЛИСТОВКА А7", "title_eng":"Listovka A7", "category":"Листовки", "category_id":"3" ,"table_name":"listovki"},
{"title":"101 X 212 ЕВРОФЛАЕР", "title_eng":"Evroflayer", "category":"Листовки", "category_id":"3" ,"table_name":"listovki"},
{"title":"92 X 152 МИНИФЛАЕР", "title_eng":"Miniflayer", "category":"Листовки", "category_id":"3" ,"table_name":"listovki"},
{"title":"422 X 299 ЛИФЛЕТ А3 В ГАРМОШКУ", "title_eng":"Liflet A3 v gormoshku", "category":"Буклеты", "category_id":"2" ,"table_name":"buklety"},
{"title":"422 X 299 ЛИФЛЕТ А3 В НАКИДКУ", "title_eng":"Liflet A3 v nakidku", "category":"Буклеты", "category_id":"2" ,"table_name":"buklety"},
{"title":"299 X 212 ЛИФЛЕТ А4 В ГАРМОШКУ", "title_eng":"Liflet A4 v gormoshku", "category":"Буклеты", "category_id":"2" ,"table_name":"buklety"},
{"title":"299 X 212 ЛИФЛЕТ А4 В НАКИДКУ", "title_eng":"Liflet A4 v nakidku", "category":"Буклеты", "category_id":"2" ,"table_name":"buklety"},
{"title":"422 X 596 ПЛАКАТ А2", "title_eng":"Plakat A2", "category":"Плакаты", "category_id":"5" ,"table_name":"plakaty"},
{"title":"299 X 422 ПЛАКАТ А3", "title_eng":"Plakat A3", "category":"Плакаты", "category_id":"5" ,"table_name":"plakaty"},
{"title":"702 X 502 ПЛАКАТ В2", "title_eng":"Plakat B2", "category":"Плакаты", "category_id":"5" ,"table_name":"plakaty"},
{"title":"299 X 212 ОТКРЫТКА", "title_eng":"Otkrytka", "category":"Открытки", "category_id":"1" ,"table_name":"otkrytky"},
{"title":"422 X 101 ЕВРООТКРЫТКА", "title_eng":"Evrootkrytka", "category":"Открытки", "category_id":"1" ,"table_name":"otkrytky"},
{"title":"422 X 101 ЕВРООТКРЫТКА 2 ФАЛЬЦА", "title_eng":"Evrootkrytka 2 falca", "category":"Открытки", "category_id":"1" ,"table_name":"otkrytky"},
{"title":"422 X 299 БУКЛЕТ А3 В А4", "title_eng":"Buklet A3 v A4", "category":"Буклеты", "category_id":"2" ,"table_name":"buklety"},
{"title":"299 X 212 БУКЛЕТ А4 В А5", "title_eng":"Buklet A4 v A5", "category":"Буклеты", "category_id":"2" ,"table_name":"buklety"},
{"title":"212 X 150 БУКЛЕТ А5 В А6", "title_eng":"Buklet A5 v A6", "category":"Буклеты", "category_id":"2" ,"table_name":"buklety"},
{"title":"150 X 107 БУКЛЕТ А6 В А7", "title_eng":"Buklet A6 v A7", "category":"Буклеты", "category_id":"2" ,"table_name":"buklety"},
{"title":"200 X 212 ЕВРОБУКЛЕТ", "title_eng":"Evrobuklet", "category":"Буклеты", "category_id":"2" ,"table_name":"buklety"},
{"title":"182 X 152 МИНИБУКЛЕТ", "title_eng":"Minibuklet", "category":"Буклеты", "category_id":"2" ,"table_name":"buklety"}
]

